services:
  - type: web
    name: astro-rag
    env: python
    buildCommand: |
      pip install -U pip setuptools wheel 
      pip install google-generativeai==0.3.2 langchain-google-genai==0.0.6
      pip install -r requirements.txt
      python verify_packages.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true
    healthCheckPath: / 